// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HolidayPlannerDbContext))]
    [Migration("20230329085238_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddicionalInformation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7737),
                            Name = "Name1",
                            Place = "Place1",
                            StartDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7701),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7744),
                            Name = "Name2",
                            Place = "Place2",
                            StartDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7743),
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7749),
                            Name = "Name3",
                            Place = "Place3",
                            StartDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7748),
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7754),
                            Name = "Name4",
                            Place = "Place4",
                            StartDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7753),
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7761),
                            Name = "Name5",
                            Place = "Place5",
                            StartDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7759),
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7767),
                            Name = "Name6",
                            Place = "Place6",
                            StartDate = new DateTime(2023, 3, 29, 9, 52, 38, 428, DateTimeKind.Local).AddTicks(7765),
                            UserId = 6
                        });
                });

            modelBuilder.Entity("DataAccess.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Password = "Password1",
                            Username = "Name1"
                        },
                        new
                        {
                            Id = 2,
                            Password = "Password2",
                            Username = "Name2"
                        },
                        new
                        {
                            Id = 3,
                            Password = "Password3",
                            Username = "Name3"
                        },
                        new
                        {
                            Id = 4,
                            Password = "Password4",
                            Username = "Name4"
                        },
                        new
                        {
                            Id = 5,
                            Password = "Password5",
                            Username = "Name5"
                        },
                        new
                        {
                            Id = 6,
                            Password = "Password6",
                            Username = "Name6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
