// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(HolidayPlannerDbContext))]
    partial class HolidayPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccess.Models.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddicionalInformation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Plans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2792),
                            Name = "Name1",
                            Place = "Place1",
                            StartDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2759)
                        },
                        new
                        {
                            Id = 2,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2799),
                            Name = "Name2",
                            Place = "Place2",
                            StartDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2797)
                        },
                        new
                        {
                            Id = 3,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2804),
                            Name = "Name3",
                            Place = "Place3",
                            StartDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2802)
                        },
                        new
                        {
                            Id = 4,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2808),
                            Name = "Name4",
                            Place = "Place4",
                            StartDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2807)
                        },
                        new
                        {
                            Id = 5,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2813),
                            Name = "Name5",
                            Place = "Place5",
                            StartDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2811)
                        },
                        new
                        {
                            Id = 6,
                            AddicionalInformation = "",
                            EndDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2819),
                            Name = "Name6",
                            Place = "Place6",
                            StartDate = new DateTime(2023, 4, 7, 10, 56, 37, 971, DateTimeKind.Local).AddTicks(2817)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
